services:
  internal:
    command: node app.js
    internalRouter: true
    build: .
    environment:
      - "*"
      - PORT=8000
    port: 8000
    scale:
      count: 1
      cpu: 250
      memory: 256
    tls:
      redirect: false
  external:
    command: node app.js
    build: .
    environment:
      - "*"
      - PORT=8000
    port: 8000
    scale:
      count: 1
      cpu: 250
      memory: 256
    # tls:
    #   redirect: false
